### ISSUE TITLE
configure supplier as resolver fails

### ISSUE THREAD

**Issue by p-e-t-e-r-m** [kirei/ansible-freeipa-mmr#2]
TASK [ipa-mmr : configure supplier as resolver] ********************************

fatal: [ipa2.x.y.z]: FAILED! => {"msg": "The task includes an option 
with an undefined variable. The error was: 'dict object' has no
attribute 'ansible_default_ipv4'\n\nThe error appears to have been in
'/home/user/ansible/ansible-freeipa-mmr/roles/ipa-mmr/tasks/replica.yml':
line 13, column 3, but may\nbe elsewhere in the file depending on the
exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name:
configure supplier as resolver\n ^ here\n\nexception type: <class
'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dict object' has
no attribute 'ansible_default_ipv4'"}

Then I have added ipa1's IP as nameserver in /etc/resolv.conf before running this.

**Comment by jschlyter** [comment]
Your play needs to collect all facts before installing, e.g.:

    - hosts: ipa_servers
       name: Gather facts from all hosts
       tasks: []

Check for this added in https://github.com/kirei/ansible-freeipa-mmr/commit/bd0c4665d8f29d60be2c487c3b8e6514a13f6bf8
